{
    "id": "CVE-2024-24549",
    "cisaKEV": false,
    "reported_exploited": false,
    "exploit_maturity": "poc",
    "counts": {
        "public_exploit_count": 1
    },
    "timeline": {
        "nvd_published": "2024-03-13"
    },
    "exploits": [
        {
            "url": "https://github.com/JFOZ1010/CVE-2024-24549",
            "name": "Proof of concept of the CVE-2024-24549, Exploit in Python. ",
            "source": "github",
            "date_added": "2024-12-09",
            "exploit_maturity": "poc"
        }
    ]
}